### ISSUE TITLE
การแจ้งข้อมูลที่จัดเก็บ ในข้อตกลงการใช้งาน อาจไม่ตรงกับที่เก็บจริง

### ISSUE THREAD

**Issue by bact** [codeforpublic/SQUID#44]
ปัจจุบันไม่ชัดเจนว่าข้อมูลที่จัดเก็บจริงจากตัวแอป กับข้อมูลที่แจ้งว่าจะเก็บในข้อตกลงการใช้งาน นั้นตรงกันหรือไม่
ทำให้เกิดความสงสัยไม่แน่ใจ สับสน หรือกังวลไปมากกว่าข้อเท็จจริง

ตัวอย่างเช่น การจัดเก็บหมายเลขโทรศัพท์ 
- ตอนลงทะเบียนไม่มีการถามข้อมูลนี้
- แต่ในข้อตกลงการใช้งาน มีพูดถึงการเก็บ https://github.com/codeforpublic/morchana-app/blob/49d340cf1d0f40272e738f0886ffdc92d012ccbc/i18n/locales/th.js#L211
- หรือแอปอ่านข้อมูลหมายเลขเอาเองจากระบบปฏิบัติการ?

ถ้าทำให้ชัดเจนได้ ก็น่าจะคลายความสับสนไปได้ครับ

**Comment by ouoam** [comment]
ผมลองเอาไปแสกน QR Code ของไทยชนะ มันจะให้กรอกเบอร์โทรศัพท์นะครับ

และจากคลิปนี้ซึ่งเป็นรุ่นเก่าไม่ใช่รุ่นปัจจุบัน https://youtu.be/2NVg-LEM3U4?t=609 จะเห็นว่ามีเมนูให้ยืนยันตัวตน

**Comment by bact** [comment]
ขอบคุณครับ อืมมม แปลว่าจะเก็บก็ต่อเมื่อเริ่มมีการ "เชื่อม" กับระบบของไทยชนะ

(ใช้คำว่าเชื่อมได้ไหม แบบว่าได้มีการสัมผัส พบเจอ กับวัตถุอะไรบางอย่างจากไทยชนะ)
