### ISSUE TITLE
Texts regarding location tracking should be removed from devices without GMS

### ISSUE THREAD

**Issue by PaperMonster** [codeforpublic/SQUID#69]
Since location tracking does not work without GMS, texts regarding matching user's location with COVID-19 patients' are not true. Location permission request (and perhaps motion permission too) should also be skipped until the app actually has this feature.
![device-2021-01-19-140759](https://user-images.githubusercontent.com/10735822/104999946-48d1c780-5a60-11eb-8205-94b0e448435b.png) ![device-2021-01-19-140821](https://user-images.githubusercontent.com/10735822/104999970-50916c00-5a60-11eb-9653-b8ce795d046e.png)
(Screenshots taken from version 2.0.3 AppGallery version)

**Comment by n3tr** [comment]
This should be fixed in https://github.com/codeforpublic/SQUID/pull/65. for now, we won't support device without GMS

**Comment by PaperMonster** [comment]
I'm aware of #65 disabling background location tracking on non-GMS devices, but what I'm proposing is removing untrue texts ("ตำแหน่งของคุณ เพื่อคอยแจ้งเตือนหากคุณได้ไปใกล้ชิดกับคนที่มีความเสี่ยง หรืออยู่ในพื้นที่เสี่ยง" and "การเคลื่อนที่ของคุณ เพื่อจัดการการใช้พลังงานของมือถืออย่างมีประสิทธิภาพ") and skipping unused permission requests (location and motion) from onboarding. In other words, just skipping to the bluetooth onboard page, or replace with some explanation. This is to prevent giving user false hope of getting notified using location history and prevent this untrue statement from ruining the app's reputation in the future.

**Comment by n3tr** [comment]
Agree, I will discuss this with the team since as I know we have a plan to support location tracking on Huawei devices as well. Let's see how the timeline looks like.
